# Exercise 2.B Cleaning up data

In [35]:
import numpy as np

In [36]:
import pandas as pd

In [37]:
df = pd.read_csv("test_data.csv")

df

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [38]:
df.describe() #statistics

            ID       Age      Score
count  8.00000   6.00000   7.000000
mean   4.50000  25.00000  66.285714
std    2.44949   6.78233  32.576650
min    1.00000  18.00000  -1.000000
25%    2.75000  19.75000  60.000000
50%    4.50000  23.50000  78.000000
75%    6.25000  29.50000  87.500000
max    8.00000  35.00000  92.000000

## Filtering a DataFrame

### FIlter age > 18

In [39]:
df_age_filtered = df[df["Age"] > 18] #df["Age"] > 18, keeps rows where age is above 18

df_age_filtered

   ID     Name   Age     City  Score
0   1   Alicia  25.0       NY   85.0
2   3  Charlie  22.0  Chicago   -1.0
3   4  Dominic  19.0  Houston   65.0
4   5      Eve  31.0  Phoenix   78.0
5   6    Frank  35.0   Boston    NaN

### FIlter score between 50 ansd 100

In [40]:
df_score_filtered = df[(df["Score"] > 50) & (df["Score"] < 100)] # & means AND

df_score_filtered

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [41]:
# Missing values (NaN) are automatically excluded in comparisons

## Modifying a DataFrame

### Remove invalid Score rows

In [42]:
df_cleaned = df[df["Score"] >= 0] #df[df["Score"] >= 0] removes invalid scores like -1

df_cleaned

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

### Remove the City column from the DataFrame

In [43]:
df_cleaned = df_cleaned.drop(columns=["City"]) # drop(columns=[...]) removes columns
 
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob   NaN   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
6   7    Grace   NaN   55.0
7   8    Heidi  18.0   90.0

### Replace all missing Age values with the mean Age of the DataFrame using fillna

In [44]:
df_cleaned["Age"] = df_cleaned["Age"].fillna(df_cleaned["Age"].mean()) # fillna(mean) replaces missing values

df_cleaned

   ID     Name    Age  Score
0   1   Alicia  25.00   85.0
1   2      Bob  23.25   92.0
3   4  Dominic  19.00   65.0
4   5      Eve  31.00   78.0
6   7    Grace  23.25   55.0
7   8    Heidi  18.00   90.0

### Replace any Score value of 0 with the mean Score of the DataFrame using replace

In [45]:
df_cleaned["Score"] = df_cleaned["Score"].replace(0, df_cleaned["Score"].mean()) # replace() swaps specific values (0 = mean score)

df_cleaned

   ID     Name    Age  Score
0   1   Alicia  25.00   85.0
1   2      Bob  23.25   92.0
3   4  Dominic  19.00   65.0
4   5      Eve  31.00   78.0
6   7    Grace  23.25   55.0
7   8    Heidi  18.00   90.0

### Remove any remaining rows that contain NaN values using the dropna function

In [46]:
df_cleaned = df_cleaned.dropna() # dropna() removes any leftover missing data 

df_cleaned

   ID     Name    Age  Score
0   1   Alicia  25.00   85.0
1   2      Bob  23.25   92.0
3   4  Dominic  19.00   65.0
4   5      Eve  31.00   78.0
6   7    Grace  23.25   55.0
7   8    Heidi  18.00   90.0

In [ ]:
###

In [47]:
df_cleaned = df_cleaned.set_index("ID") # set_index("ID") uses ID as row labels

df_cleaned

       Name    Age  Score
ID
1    Alicia  25.00   85.0
2       Bob  23.25   92.0
4   Dominic  19.00   65.0
5       Eve  31.00   78.0
7     Grace  23.25   55.0
8     Heidi  18.00   90.0