# Excercise 2.C Working with Multiple DataFrames

In [1]:
import numpy as np

In [2]:
import pandas as pd

## Basic Aggregations

In [3]:
data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'],
    'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
    'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]
}

df_sales = pd.DataFrame(data)
df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

In [4]:
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']
df_sales
# df_sales['Column_Name'] Accesses or creates a column in the DataFrame
# (=) Stores the result as a new or updated column

#df_sales['Revenue'] accesses/creates a column in the DataFrame
# df_sales['Units_Sold'] * df_sales['Price'] multiplies values row-by-row

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [16]:
# df_sales['Units_Sold'] selects the Units_Sold column from the DataFrame
# .sum() adds up all values in that column to get the total
total_units_sold = df_sales['Units_Sold'].sum()
total_revenue = df_sales['Revenue'].sum()
# df_sales['Revenue'] selects the Revenue column
# .sum() calculates the total revenue across all rows
print("Total Units Sold:", total_units_sold)
print("Total Revenue:", total_revenue)

Total Units Sold: 105
Total Revenue: 16000

In [17]:
# df_sales['Units_Sold'] selects the Units_Sold column from the DataFrame
# .mean() calculates the average (mean) of all values in that column
average_units_sold = df_sales['Units_Sold'].mean()
average_revenue = df_sales['Revenue'].mean()
# df_sales['Revenue'] selects the Revenue column
# .mean() computes the average revenue across all rows
print("Average Units Sold:", average_units_sold)
print("Average Revenue:", average_revenue)

Average Units Sold: 11.666666666666666
Average Revenue: 1777.7777777777778

## Grouping Data

### Group by Product (Total Units & Revenue)

In [15]:
grouped_product = df_sales.groupby('Product')[['Units_Sold', 'Revenue']].sum() #groupby() splits data into groups based on column(s)/ sum() adds values within each group
grouped_product 

#groupby('Product') splits the DataFrame into groups based on unique values in the 'Product' column
# [['Units_Sold', 'Revenue']] selects only the columns we want to aggregate
# .sum() adds up all values within each group for those columns

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

### Group by Region (Average Units & Revenue)

In [14]:
grouped_region = df_sales.groupby('Region')[['Units_Sold', 'Revenue']].mean() # mean() calculates averages within each group
grouped_region
# groupby('Region') groups the data based on each unique region
# [['Units_Sold', 'Revenue']] selects columns to calculate statistics on
# .mean() calculates the average (mean) value for each group

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

### Group by Product and Region (Sum of Units & Revenue)

In [13]:
grouped_product_region = df_sales.groupby(['Product', 'Region'])[['Units_Sold', 'Revenue']].sum() # [['col1', 'col2']] → selects specific columns to work with
grouped_product_region
# groupby(['Product', 'Region']) creates multi-level grouping (hierarchical index)
# This means data is grouped by each unique combination of Product AND Region
# [['Units_Sold', 'Revenue']] selects the relevant numeric columns
# .sum() computes the total for each Product-Region combination

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

### Sort by Units_Sold (Ascending)

In [19]:
# sort_values() is used to sort a DataFrame by a specific column
# 'Units_Sold' is the column we are sorting by
# ascending=True sorts from smallest to largest
sorted_units = df_sales.sort_values(by='Units_Sold', ascending=True) # by=  Specifies which column to sort

sorted_units

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
0       A  North          10    100     1000
4       B  North          10    200     2000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

### Sort by Revenue (Descending)

In [20]:
# sort_values() sorts the data based on 'Revenue'
# ascending=False sorts from highest to lowest
sorted_revenue = df_sales.sort_values(by='Revenue', ascending=False) # ascending=False Sorts from highest to lowest

sorted_revenue

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [21]:
# rank() assigns a rank to each value in the column
# ascending=False means highest value gets rank 1
# method='dense' makes sure that ranks have no gaps in-between 
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending=False, method='dense') 
#rank() Assigns a numerical ranking to values/method='dense'Prevents skipped ranking numbers (For exp: 1,2,3 instead of 1,2,4)

df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           4.0
1       B  South          15    200     3000           1.0
2       C   East          20    150     3000           1.0
3       A   West           5    100      500           5.0
4       B  North          10    200     2000           3.0
5       C  South          15    150     2250           2.0
6       A   East          10    100     1000           4.0
7       B   West           5    200     1000           4.0
8       C  North          15    150     2250           2.0

## Merging DataFrames

### Create df_products

In [23]:
# Define product data using a dictionary
# Keys become column names, values are the data for each column
product_data = {
    'Product': ['A', 'B', 'C'],
    'Category': ['Electronics', 'Furniture', 'Appliances']
}

# pd.DataFrame() Converts structured data into a table format
df_products = pd.DataFrame(product_data) 

df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

### Merge DataFrames

In [26]:
# pd.merge() combines two DataFrames based on a common column
# 'on="Product"' specifies the column both DataFrames share
df_merged = pd.merge(df_sales, df_products, on='Product')
# Default join = inner join (only matching values kept)
df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           4.0  Electronics
1       B  South          15    200     3000           1.0    Furniture
2       C   East          20    150     3000           1.0   Appliances
3       A   West           5    100      500           5.0  Electronics
4       B  North          10    200     2000           3.0    Furniture
5       C  South          15    150     2250           2.0   Appliances
6       A   East          10    100     1000           4.0  Electronics
7       B   West           5    200     1000           4.0    Furniture
8       C  North          15    150     2250           2.0   Appliances

In [ ]:
# groupby('Category') groups the merged data by product category
# ['Revenue'] selects the column we want to aggregate
# .sum() calculates total revenue for each category
revenue_by_category = df_merged.groupby('Category')['Revenue'].sum()

revenue_by_category